name: Deploy to server

on:
  push:
    branches:
      - main
      - web-dev

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call external API
        run: |
          curl 'https://admin.serenitytrail.xyz/devops/start'
